-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `dev`;
USE SCHEMA `bronze`;

-- COMMAND ----------

SELECT * from samples.nyctaxi.trips

-- COMMAND ----------

select * from read_files("/Volumes/dev/bronze/raw/sales/sales.csv",format=>"csv")

-- COMMAND ----------

select distinct * from dev.bronze.sales

-- COMMAND ----------


